export type BlogPost = {
  id?: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  author: string;
  sourceUrl: string;
  image: string | null;
  contentHtml: string;
  featured?: boolean;
  tag?: string;
};

// Generated by scripts/sync-substack.mjs
export const blogPosts: BlogPost[] = [
  {
    "id": "blog-test",
    "title": "test",
    "slug": "test",
    "excerpt": "test",
    "publishedAt": "Fri, 06 Mar 2026 21:01:19 GMT",
    "author": "Together Sports",
    "sourceUrl": "https://togethersports.substack.com/p/test",
    "image": "https://substackcdn.com/image/fetch/$s_!Ax51!,w_256,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F598a2bd9-401a-4fba-8b63-94a3c80513c5_144x144.png",
    "contentHtml": "<p>testestetztstetteetsetsstest</p>",
    "featured": true,
    "tag": ""
  }
] as BlogPost[];
